version: '3'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - db.env
    networks:
      - proxy-tier

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - VIRTUAL_HOST=phpmyadmin.vworkspace.cloud
      - LETSENCRYPT_HOST=phpmyadmin.vworkspace.cloud
      - LETSENCRYPT_EMAIL=binhk57cd@gmail.com
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
    networks:
      - proxy-tier

  nextcloud:
    build: ./app
    # image: luongquy/vworkspace:25.0.0
    container_name: nextcloud
    restart: always
    volumes:
      - html:/var/www/html
      - config:/var/www/html/config
      - data:/var/www/html/data
      - themes:/var/www/html/themes
      - custom_apps:/var/www/html/custom_apps
    environment:
      - VIRTUAL_HOST=vworkspace.cloud
      - LETSENCRYPT_HOST=vworkspace.cloud
      - LETSENCRYPT_EMAIL=binhk57cd@gmail.com
      - MYSQL_HOST=mariadb
        #- NEXTCLOUD_ADMIN_USER=admin
        #- NEXTCLOUD_ADMIN_PASSWORD=admin@123
        # - NEXTCLOUD_TRUSTED_DOMAINS=vworkspace.cloud
        #- NEXTCLOUD_THEME=vworkspace_theme
        #- OBJECTSTORE_S3_BUCKET=vworkspace-production
        #- OBJECTSTORE_S3_KEY=AKIAXBO4ZPSJFFQGGBJH
        #- OBJECTSTORE_S3_SECRET=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
        #- OBJECTSTORE_S3_REGION=ap-southeast-1
        #- OBJECTSTORE_S3_AUTOCREATE=true
        #- OBJECTSTORE_S3_SSL=true
    env_file:
      - db.env
    depends_on:
      - mariadb
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  mariadb:
  data:
  config:
  themes:
  custom_apps:
  certs:
  vhost.d:
  html:
  acme:

networks:
  proxy-tier:
